### ISSUE TITLE
Serializer fails with empty vector

### ISSUE THREAD

**Issue by balazsdukai** [3DBAG/roofer#64]
Error: `Failed to serialize /objects/NL.IMBAG.Pand.0603100000011074/reconstruct/NL.IMBAG.Pand.0603100000011074.city.jsonl. vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)`

**Comment by balazsdukai** [comment]
Added a test case `issue-64` for this.

**Comment by Ylannl** [comment]
This should be fixed with 288aeed077e7f943f99ea414f59e0a34a8e3e7c3.
