### ISSUE TITLE
Build error 'LINK : fatal error LNK1104: cannot open file 'mimalloc.lib'

### ISSUE THREAD

**Issue by bertt** [3DBAG/roofer#65]
Hi,

I'm trying to build the tool on Windows following the instructions on https://innovation.3dbag.nl/roofer/getting_started.html but I'm getting a build error on step 'cmake --build build':

LINK : fatal error LNK1104: cannot open file 'mimalloc.lib' [D:\dev\github.com\3DBag\roofer\build\apps\roofer-app\roofe
r.vcxproj]

Any idea how to fix this? 

<details><summary>Build details</summary>
D:\dev\github.com\3DBag\roofer>cmake --build build
MSBuild version 17.12.6+db5f6012c for .NET Framework

  1>Checking Build System
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/core/common/CMakeLists.txt
  Raster.cpp
  GridPIPTester.cpp
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\xutility(5201,24): warning C4
244: '=': conversion from 'const _Ty' to 'float', possible loss of data [D:\dev\github.com\3DBag\roofer\build\src\core\
common\common.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\xutility(5201,24): warning C4
244:         with [D:\dev\github.com\3DBag\roofer\build\src\core\common\common.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\xutility(5201,24): warning C4
244:         [ [D:\dev\github.com\3DBag\roofer\build\src\core\common\common.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\xutility(5201,24): warning C4
244:             _Ty=double [D:\dev\github.com\3DBag\roofer\build\src\core\common\common.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\xutility(5201,24): warning C4
244:         ] [D:\dev\github.com\3DBag\roofer\build\src\core\common\common.vcxproj]
  (compiling source file '../../../../src/core/common/Raster.cpp')
      D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\xutility(5201,24):
      the template instantiation context (the oldest one first) is
          D:\dev\github.com\3DBag\roofer\src\core\common\Raster.cpp(76,12):
          see reference to function template instantiation 'void std::fill<std::_Vector_iterator<std::_Vector_val<std::
  _Simple_types<_Ty>>>,double>(const _FwdIt,const _FwdIt,const double &)' being compiled
          with
          [
              _Ty=float,
              _FwdIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<float>>>
          ]

  common.cpp
  Generating Code...
  common.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\core\common\common.dir\Debug\common.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/extra/io/CMakeLists.txt
  CityJsonWriter.cpp
  PointCloudReaderLASlib.cpp
  PointCloudWriterLASlib.cpp
  RasterWriterGDAL.cpp
  StreamCropper.cpp
  VectorReaderOGR.cpp
  VectorWriterOGR.cpp
  SpatialReferenceSystemOGR.cpp
  Generating Code...
D:\dev\github.com\3DBag\roofer\src\extra\io\StreamCropper.cpp(255,1): warning C4700: uninitialized local variable 'poly
_i' used [D:\dev\github.com\3DBag\roofer\build\src\extra\io\io.vcxproj]
  io.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\extra\io\io.dir\Debug\io.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/core/logger/CMakeLists.txt
  logger.cpp
  logger_spdlog.cpp
  Generating Code...
  logger.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\core\logger\logger.dir\Debug\logger.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/extra/misc/CMakeLists.txt
  NodataCircleComputer.cpp
  PC2MeshDistCalculator.cpp
  PointcloudRasteriser.cpp
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(31,26): warning C4244
: '=': conversion from 'float' to '_Ty', possible loss of data [D:\dev\github.com\3DBag\roofer\build\src\extra\misc\mis
c.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(31,26): warning C4244
:         with [D:\dev\github.com\3DBag\roofer\build\src\extra\misc\misc.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(31,26): warning C4244
:         [ [D:\dev\github.com\3DBag\roofer\build\src\extra\misc\misc.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(31,26): warning C4244
:             _Ty=int [D:\dev\github.com\3DBag\roofer\build\src\extra\misc\misc.vcxproj]
D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(31,26): warning C4244
:         ] [D:\dev\github.com\3DBag\roofer\build\src\extra\misc\misc.vcxproj]
  (compiling source file '../../../../src/extra/misc/PointcloudRasteriser.cpp')
      D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(31,26):
      the template instantiation context (the oldest one first) is
          D:\dev\github.com\3DBag\roofer\src\extra\misc\PointcloudRasteriser.cpp(144,20):
          see reference to function template instantiation '_Ty std::accumulate<std::_Vector_iterator<std::_Vector_val<
  std::_Simple_types<float>>>,int>(const _InIt,const _InIt,_Ty)' being compiled
          with
          [
              _Ty=int,
              _InIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<float>>>
          ]
          D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include\numeric(42,17):
          see reference to function template instantiation '_Ty std::accumulate<_InIt,_Ty,std::plus<void>>(const _InIt,
  const _InIt,_Ty,_Fn)' being compiled
          with
          [
              _Ty=int,
              _InIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<float>>>,
              _Fn=std::plus<void>
          ]

  projHelper.cpp
  select_pointcloud.cpp
  Vector2DOpsGEOS.cpp
  Generating Code...
  misc.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\extra\misc\misc.dir\Debug\misc.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/core/common/CMakeLists.txt
  ptinpoly.c
D:\dev\github.com\3DBag\roofer\src\core\common\ptinpoly.c(141,10): warning C4133: '=': incompatible types - from 'pPipo
int' to 'double *' [D:\dev\github.com\3DBag\roofer\build\src\core\common\ptinpoly.vcxproj]
D:\dev\github.com\3DBag\roofer\src\core\common\ptinpoly.c(143,7): warning C4133: '=': incompatible types - from 'pPipoi
nt' to 'double *' [D:\dev\github.com\3DBag\roofer\build\src\core\common\ptinpoly.vcxproj]
  ptinpoly.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\core\common\ptinpoly.dir\Debug\ptinpoly.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/core/reconstruction/CMakeLists.txt
  AlphaShaper.cpp
  ArrangementBase.cpp
  ArrangementBuilder.cpp
  ArrangementDissolver.cpp
  ArrangementExtruder.cpp
  ArrangementOptimiser.cpp
  ArrangementSnapper.cpp
  ElevationProvider.cpp
  cdt_util.cpp
  LineDetector.cpp
  LineDetectorBase.cpp
  LineRegulariser.cpp
  LineRegulariserBase.cpp
  MeshTriangulatorLegacy.cpp
  PlaneDetector.cpp
  PlaneIntersector.cpp
  SegmentRasteriser.cpp
  SimplePolygonExtruder.cpp
  Generating Code...
  reconstruction.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\core\reconstruction\reconstruction.dir\Debug\recon
  struction.lib
  1>Checking the git repository for changes...
  Building Custom Rule D:/dev/github.com/3DBag/roofer/build/_deps/cmake-git-version-tracking-src/CMakeLists.txt
  Building Custom Rule D:/dev/github.com/3DBag/roofer/build/_deps/cmake-git-version-tracking-src/CMakeLists.txt
  git.c
  cmake_git_version_tracking.vcxproj -> D:\dev\github.com\3DBag\roofer\build\_deps\cmake-git-version-tracking-build\Deb
  ug\cmake_git_version_tracking.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/core/CMakeLists.txt
  roofer-core.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\core\Debug\roofer-core.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/src/extra/CMakeLists.txt
  roofer-extra.vcxproj -> D:\dev\github.com\3DBag\roofer\build\src\extra\Debug\roofer-extra.lib
  Building Custom Rule D:/dev/github.com/3DBag/roofer/apps/roofer-app/CMakeLists.txt
  doc-helper.cpp
  doc-helper.vcxproj -> D:\dev\github.com\3DBag\roofer\build\apps\roofer-app\Debug\doc-helper.exe
  Building Custom Rule D:/dev/github.com/3DBag/roofer/apps/reconstruct/CMakeLists.txt
  reconstruct.cpp
  reconstruct.vcxproj -> D:\dev\github.com\3DBag\roofer\build\apps\reconstruct\Debug\reconstruct.exe
  Building Custom Rule D:/dev/github.com/3DBag/roofer/apps/roofer-app/CMakeLists.txt
  roofer-app.cpp
LINK : fatal error LNK1104: cannot open file 'mimalloc.lib' [D:\dev\github.com\3DBag\roofer\build\apps\roofer-app\roofe
r.vcxproj]
</details>

**Comment by Ylannl** [comment]
Could you try with #68 ? Unfortunately the automated windows build is failing due to another issue, but this should fix your issue.

**Comment by bertt** [comment]
yes thanks it's fixed with https://github.com/3DBAG/roofer/pull/68
